config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'

  # get 'password_resets/edit'

  #~ get 'sessions/new'
  #~ get 'users/new'
  #** must comment out since we're setting root page to home anyways
  # get 'static_pages/home'


  # You can have the root of your site routed with "root"
  root 'static_pages#home'
  #** This changes the URL static_pages/home to the controller/action pair static_pages#home
  #** which ensures that the GET requests for / get routed to the home action in the Static Pages controller
  
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  #** [ 5.3.2:22 ] Routes for static pages
  #** routes a GET request for the URL /help to the help action in the static
  #** Pages controller, so that we can use the URL /help in place of /static_pages/help
  #** 2 named routes get created, help_path + help_url
  # [ 5.3.4:33 -> home.html.erb] Add named route for signup page
  
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  #                 [ 8.1.1:1 -> sessions/new.html.erb ]
  # Unlike the Users resource, which used the special resources method to obtain
  # a full suite of RESTful routes automatically (index, show, new, create, edit
  # update, destroy)
  # The sessions resources will only use named routes, handling GET and POST
  # requests witht he login route and DELETE request with the logout route
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  # [ 12.2.2 -> shared/_stats.html.erb]
  # adding a following and followers actions to the Users controller
  
  
  

  resources :users
  #                  [7.1.2:3 -> show.html.erb] 
  # This endows our app with all actions needed for our RESTful Users 
  # resource, along with a large number of named routes. 
  # At this point, since most of these actions (edit, delete, update, etc)
  # actions for the Users controller hasn't been made yet, we are going to get an error
  

  resources :account_activations, only: [:edit]
  # [ 10.1.1:1 -> [timestamp]_add_activation_to_users.rb ] Adding resource for account activations
  # because the activation link will be modifying the user's activatiions tatus,
  #we'll plan to use the edit action. this requires an Account Actv controller
  # This line will set a named route for the edit action
  
  
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # [ 10.2.1:37 -> sessions/new.html.erb ] adding resource for password resets
  # bc we'll need forms both for creating new password resets and for updating
  # them by changing the password in the User model, we need routes for
  # new, create, edit, and update
  
  
  resources :microposts,          only: [:create, :destroy]
  # [ 11.3.1:29 -> microposts_controller_test.rb ] routes for Microposts resources
  # Provides two RESTful routes, create and destroy.
  
  
  resources :relationships,       only: [:create, :destroy]
  # [ 12.2.2:20 -> views/user/_follow.html.erb]
  # Adding routes for user relationships, similar to microposts
  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]  
  before_action :check_expiration, only: [:edit, :update]
  # applies to both edit andupdate actions
  
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end
  # [ 10.2.1:41 -> user.rb ] create action for password resets
  # use create b/c we need to create a new digest


  def edit
  end
  
  
  def update
    if password_blank?
      flash.now[:danger] = "Password can't be blank"
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  
  private


    def user_params
      params.require(:user).permit(:password, :password_confirmation)
      # All the user is allowed to work with.
    end

    # Returns true if password is blank.
    def password_blank?
      params[:user][:password].blank?
    end
    
    
    
    #Before Filters
    
    def get_user
      @user = User.find_by(email: params[:email])
      
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
    
end

# [ 10.2.4:51 -> models/user.rb ] edit action for password reset
#** to get form to render, we need to define a user variable
#** We then need to verify that the user is valid, i.e., that it exists, is
#&**activated, and is authenticated according to the reset token from params[:id] 

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>
   

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<!--       ] 10.2.4:50 -> password_resets_controller ] form to reset password
Similar to updating user edit view, but we only want to work with password and
confirmation field
The email will automatically be available in the edit action because of its 
presence in the link above, but after we submit the form its value will be lost.
 solution is to use a hidden field to place (but not display) the email on the
 page, and then submit it along with the rest of the form’s information.
-->

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<!--    [ 10.2.1:40 -> passwod_resets_controller.rb ] 
Add new password reset view
-->