config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'

  # get 'password_resets/edit'

  #~ get 'sessions/new'
  #~ get 'users/new'
  #** must comment out since we're setting root page to home anyways
  # get 'static_pages/home'


  # You can have the root of your site routed with "root"
  root 'static_pages#home'
  #** This changes the URL static_pages/home to the controller/action pair static_pages#home
  #** which ensures that the GET requests for / get routed to the home action in the Static Pages controller
  
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  #** [ 5.3.2:22 ] Routes for static pages
  #** routes a GET request for the URL /help to the help action in the static
  #** Pages controller, so that we can use the URL /help in place of /static_pages/help
  #** 2 named routes get created, help_path + help_url
  # [ 5.3.4:33 -> home.html.erb] Add named route for signup page
  
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  #                 [ 8.1.1:1 -> sessions/new.html.erb ]
  # Unlike the Users resource, which used the special resources method to obtain
  # a full suite of RESTful routes automatically (index, show, new, create, edit
  # update, destroy)
  # The sessions resources will only use named routes, handling GET and POST
  # requests witht he login route and DELETE request with the logout route
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  # [ 12.2.2 -> shared/_stats.html.erb]
  # adding a following and followers actions to the Users controller
  
  
  

  resources :users
  #                  [7.1.2:3 -> show.html.erb] 
  # This endows our app with all actions needed for our RESTful Users 
  # resource, along with a large number of named routes. 
  # At this point, since most of these actions (edit, delete, update, etc)
  # actions for the Users controller hasn't been made yet, we are going to get an error
  

  resources :account_activations, only: [:edit]
  # [ 10.1.1:1 -> [timestamp]_add_activation_to_users.rb ] Adding resource for account activations
  # because the activation link will be modifying the user's activatiions tatus,
  #we'll plan to use the edit action. this requires an Account Actv controller
  # This line will set a named route for the edit action
  
  
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # [ 10.2.1:37 -> sessions/new.html.erb ] adding resource for password resets
  # bc we'll need forms both for creating new password resets and for updating
  # them by changing the password in the User model, we need routes for
  # new, create, edit, and update
  
  
  resources :microposts,          only: [:create, :destroy]
  # [ 11.3.1:29 -> microposts_controller_test.rb ] routes for Microposts resources
  # Provides two RESTful routes, create and destroy.
  
  
  resources :relationships,       only: [:create, :destroy]
  # [ 12.2.2:20 -> views/user/_follow.html.erb]
  # Adding routes for user relationships, similar to microposts
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!--          [ 7.3.3:19 -> custom.css.scss ] 
1) errors.count => number of errors
2) errors.any? => T/F
pluralize(@user.errors.count, "error") => takes an integer arg and then returns
the number with a properly pluralized version of its 2nd argument.

-->

<!--         [ 11.3.1:39 -> new.html.erb ]
Error message that work with other objects

-->

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

<!-- [ 11.3.3:46 ->  home.html.erb ] status feed partial
1) defers the rendering to the micropost partial defined
2) Here Rails knows to call the micropost partial because each element of
@feed_items has class Micropost. This causes Rails to look for a partial with the 
corresponding name in the views directory of the given resource
app/views/microposts/_micropost.html.erb
-->

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <!--f.object is  @micropost
   we pass form variable f to the partial and access the associated object
   through f.object, so that in form_for(@micropost) do |f|
   f.object is @micropost.
  -->
<div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

<!-- [ 11.3.1.:37 -> static_pages_controller.rb ] 
Form partial for creating microposts

-->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

<!-- [ 12.2.2:16 -> static_pages/home.html.erb ] 
partial for displaying followers stats
@user ||= current_user => @user = @user || current_user
-->

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>


<!--     [ 11.3.1:36 -> _micropost_form.html_erb ] partial for user info sidear

will display total number of microposts for the user

-->