config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'

  # get 'password_resets/edit'

  #~ get 'sessions/new'
  #~ get 'users/new'
  #** must comment out since we're setting root page to home anyways
  # get 'static_pages/home'


  # You can have the root of your site routed with "root"
  root 'static_pages#home'
  #** This changes the URL static_pages/home to the controller/action pair static_pages#home
  #** which ensures that the GET requests for / get routed to the home action in the Static Pages controller
  
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  #** [ 5.3.2:22 ] Routes for static pages
  #** routes a GET request for the URL /help to the help action in the static
  #** Pages controller, so that we can use the URL /help in place of /static_pages/help
  #** 2 named routes get created, help_path + help_url
  # [ 5.3.4:33 -> home.html.erb] Add named route for signup page
  
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  #                 [ 8.1.1:1 -> sessions/new.html.erb ]
  # Unlike the Users resource, which used the special resources method to obtain
  # a full suite of RESTful routes automatically (index, show, new, create, edit
  # update, destroy)
  # The sessions resources will only use named routes, handling GET and POST
  # requests witht he login route and DELETE request with the logout route
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  # [ 12.2.2 -> shared/_stats.html.erb]
  # adding a following and followers actions to the Users controller
  
  
  

  resources :users
  #                  [7.1.2:3 -> show.html.erb] 
  # This endows our app with all actions needed for our RESTful Users 
  # resource, along with a large number of named routes. 
  # At this point, since most of these actions (edit, delete, update, etc)
  # actions for the Users controller hasn't been made yet, we are going to get an error
  

  resources :account_activations, only: [:edit]
  # [ 10.1.1:1 -> [timestamp]_add_activation_to_users.rb ] Adding resource for account activations
  # because the activation link will be modifying the user's activatiions tatus,
  #we'll plan to use the edit action. this requires an Account Actv controller
  # This line will set a named route for the edit action
  
  
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # [ 10.2.1:37 -> sessions/new.html.erb ] adding resource for password resets
  # bc we'll need forms both for creating new password resets and for updating
  # them by changing the password in the User model, we need routes for
  # new, create, edit, and update
  
  
  resources :microposts,          only: [:create, :destroy]
  # [ 11.3.1:29 -> microposts_controller_test.rb ] routes for Microposts resources
  # Provides two RESTful routes, create and destroy.
  
  
  resources :relationships,       only: [:create, :destroy]
  # [ 12.2.2:20 -> views/user/_follow.html.erb]
  # Adding routes for user relationships, similar to microposts
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <!--**instead of using about_path, we can stub it with '#', which would
      make the link clickable, but go nowhere-->
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>


    <!-- [ 5.3.3:24 -> test/integration/site_layout_test.rb ] Adding links to Footer partial
    1) Use function link_to by using proper named routes
    -->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    
    <!-- [ 5.3.3:23 -> _footer.html.erb ] Adding links to Header partial
    1) Use function link_to by using proper named routes
    2) Link logo to root_path as well
    -->
    
    <!--     [ 8.2.3:16 -> app/assets/javascripts/application.js ] Changing layout links for logged-in users
    Using embedded ruby to use helper function logged_in? to check 
    -->
    
    <!-- [ 9.1.1:4 -> user_controller.rb ] Adding Url to the "settings" link in the site layout
    Since we added resources :users, it endows our app with all actions for 
    RESTful Users resource along with a lot of named routes
    -->
    
    <!--     [ 9.3.1:36 -> db/seeds.rb ] Adding URL to users link
      Use the last unused named route  
    -->

app/views/layouts/_shim.html.erb
    <!-- This is a partial. It contains code that was cluttering up the layout
    but since it could be logically separated from the full code, we put it
    in a partial. This is for ease of reading-->
    
    
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      <!-- [| 7.1.1:1] Display debug info only if in development env -->
    </div>
  </body>
</html>

<!--             [ 7.4.2:25 -> users_signup_test.rb ]
in the create action, the message is inserted into the flash template, and so 
the HTML code for flash[:success] = "..." appears as
    <div class="alert alert-success">Welcome to the Twitter Clone!"</div> 
Which is only executed per successful Sign Up. Thus this portion of code does 
not always act. 
-->




<!--
The render method is used on partials. Partials are logical groupings of code
that could be package separately. 
We put these partials that are on every page in the layouts

-->